### PR TITLE
translations 18 June 2018

### PR DESCRIPTION
**Pull request by patogit**
translations from translatewiki.net

### CODE REVIEW

**Comment by patogit** [comment]
might need to add new languages to menu, that can happen in a separate pull request

**Comment by aparcar** [comment]
Yes please adapt it here https://github.com/libremesh/chef/blob/master/chef.html#L27

**Comment by aparcar** [comment]
I'd merge now if you have no further changes?

**Comment by patogit** [comment]
I think merge now and I'll add the new languages in a separate pull request

**Pull request merged**
