### PR TITLE
translation updates, a bit messy

### PR DESCRIPTION
**Pull request by patogit**
I resolved a bunch of conflicts by hand. I see that this for some reason includes some commits that were already merged, but I think it's ok anyways.

### CODE REVIEW

**Comment by aparcar** [comment]
Please clean this up. I'll not merge the PR if it adds various temporary files accidentally added

**Comment by patogit** [comment]
I do not know how to make this work any other way. All my attempts to create something simpler failed. Suggestions welcome.

**Comment by aparcar** [comment]
Please remove all files suffixed with a ~ and type `git add .`. I can do the squashing

**Comment by patogit** [comment]
> Please remove all files suffixed with a ~ and type `git add .`. I can do the squashing

@aparcar I removed the files using the GitHub web UI.

**Comment by aparcar** [comment]
Nice, please add Arabic to the language dropdown menu.

**Pull request merged**
